export default {
  startScreen: 'guest/start',
  loginScreen: 'guest/login',
  welcomingScreen: 'guest/welcomingScreen',
  magicLogin: 'guest/magicLogin',
  search: 'authed/search',
  profileDetail: 'authed/profileDetail',
  organization: 'authed/organization',
  favourite: 'authed/favourite',
  settings: 'authed/settings',
  editProfile: 'authed/editProfile',
  navigationsList: 'authed/navigationList',
  workspace: 'authed/workspace',
  eventDetail: 'authed/eventDetail',
  eventList: 'authed/eventList',
  eventSchedule: 'authed/schedule',
  serviceTerms: 'authed/serviceTerms',
  privacyPolicy: 'authed/privacyPolicy',
  myQREventTicket: 'authed/myQREventTicket',
  sameTopicUserListScreen: 'authed/sameTopicUserListScreen'
};
