export default {
  searchNew: 'searchNew',
  profileDetail: 'profileDetail',
  organization: 'organization',
  favourite: 'favourite',
  settings: 'settings',
  editProfile: 'editProfile',
  navigationsList: 'navigationList',
  workspace: 'workspace',
  eventDetail: 'eventDetail',
  eventList: 'eventList',
  eventSchedule: 'schedule',
  serviceTerms: 'serviceTerms',
  privacyPolicy: 'privacyPolicy',
  loginScreen: 'loginScreen',
  welcomingScreen: 'welcomingScreen',
  myQREventTicket: 'myQREventTicket',
  sameTopicUserList: 'sameTopicUserList',
  magicLogin: 'magicLogin'
};
