import tokeys from 'tokeys';

export default tokeys([
  'GET_USER',
  'FILTER_SEARCH',
  'GET_USER_DETAIL',
  'GET_MY_PROFILE_DETAIL',
  'ENDORSE_USER',
  'REMOVE_ENDORSE_USER',
  'FAVOURITE_USER',
  'REMOVE_FAVOURITE_USER',
  'GET_FAVOURITE_USERS',
  'GET_MATCH_RECOMMENDATION'
]);
